Add command in package.json for backend and frontend for executing config-const

diff --git a/config-const b/config-const
--- a/config-const
+++ b/config-const
@@ -70,7 +70,7 @@ while getopts h flag ; do
       HELP=t
       ;;
     ?)
-      echo "Invalid flag" && exit 0
+      echo "Invalid flag" && exit 1
       ;;
   esac
 done
